---
linters:
  disable-all: true
  enable:
    - "gofmt"
    - "gosimple"
    - "govet"
    - "ineffassign"
    - "makezero"
    - "misspell"
    - "nakedret"
    - "nilerr"
    - "staticcheck"
    - "structcheck"
    - "unconvert"
    - "unused"

run:
  timeout: '2m'
