---
linters:
  enable-all: true
  disable:
    # Temporary
    #- 'depguard'
    #- 'gomoddirectives'
    #- 'nosnakecase'
    #- 'paralleltest'
    #- 'persprintf'
    #- 'thelper'
    #- 'varnamelen'
    #- 'wrapcheck'
    #- 'wsl'
    
    # Deprecated
    - 'exportloopref'
