# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  binary: terraform-provider-unifi_v{{.Version}}
  goos:
    - freebsd
    - openbsd
    - solaris
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: arm64
    - goos: openbsd
      goarch: arm
    - goos: openbsd
      goarch: arm64
    - goos: solaris
      goarch: arm
    - goos: solaris
      goarch: arm64
    - goos: solaris
      goarch: '386'
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    # darwin: Darwin
    # linux: Linux
    # windows: Windows
    # 386: i386
    # amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
# signs:
#   - artifacts: checksum
release:
  draft: true
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
  # sort: asc
  # filters:
  #   exclude:
  #   - '^docs:'
  #   - '^test:'
