---
services:
  unifi:
    image: "jacobalberty/unifi:${UNIFI_VERSION:-latest}"
    init: true
    restart: "always"
    environment:
      PKGURL: "${UNIFI_DOWNLOAD_URL:-}"
      UNIFI_STDOUT: "true"
    ports:
      - "${UNIFI_HTTP_PORT:-8080}:8080/tcp"
      - "${UNIFI_HTTPS_PORT:-8443}:8443/tcp"
    volumes:
      - "./scripts/init.d:/usr/local/unifi/init.d:ro"
